aiAgent:
  image:
    repository: ghcr.io/rancher/rancher-ai-agent
    tag: v0.1.2-alpha.19
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: ghcr.io/rancher/rancher-ai-mcp
    tag: v0.1.2-alpha.4
    pullPolicy: IfNotPresent

llmModel: ""
ollamaLlmModel: ""
geminiLlmModel: ""
openaiLlmModel: ""
bedrockLlmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
openaiUrl:
awsBedrock:
  bearerToken:
  accessKeyId:
  secretAccessKey:
  region:
activeLlm: # ollama, gemini, openai, bedrock
# Enable RAG with embedded rancher documentation
rag:
    enabled: false
    embeddings_model:
    pvc:
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
storage:
  enabled: false
  connectionString: ""
probes:
  startup:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 10
  liveness:
    initialDelaySeconds: 0
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2
insecureSkipTls: false
llmMock:
  enabled: false
  url: ""
log:
  level: info
